# roles/clickhouse_instance/tasks/manage_service.yml

---
- name: Template systemd service for instance {{ instance }}
  template:
    src: "systemd/clickhouse.service.j2"
    dest: "/etc/systemd/system/clickhouse-{{ instance }}.service"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd
    - Restart ClickHouse instance {{ instance }}

- name: Enable and start ClickHouse service for instance {{ instance }}
  systemd:
    name: clickhouse-{{ instance }}
    enabled: yes
    state: started
